config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
  resources :authors
  resources :author_sessions, only: [:new, :create, :destroy]

  get 'login' => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
  get 'most_viewed' => 'articles#most_viewed'
  get 'feed' => 'articles#feed'
end

app/models/article.rb
class Article < ActiveRecord::Base
	has_many :comments
	has_many :taggings
	has_many :tags, through: :taggings
	belongs_to :author

	has_attached_file :image, styles: { medium: "500", thumb: "320" }, :convert_options => { :thumb => "-quality 75" }
	# has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" } # part of paperclip library
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	def tag_list
		tags.join(", ")
	end

	def tag_list=(tags_string)
		tag_names = tags_string.split(",").collect { |s| s.strip.downcase }.uniq
		new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by(name: name) }
		self.tags = new_or_found_tags
	end

	def increment_view_count
		self.view_count += 1
	end
end

app/models/author.rb
class Author < ActiveRecord::Base
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  validates_uniqueness_of :username
  validates :username, presence: true
  validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}

  # Validates that password is always present. Allow nil for update.
  validates :password, presence: true, allow_nil: true

  has_many :articles

  def to_s
  	username
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_many :taggings
	has_many :articles, through: :taggings

	def to_s
		name
	end
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	before_filter :require_login, only: [:new, :create, :edit, :update]

	include ArticlesHelper

	def index 
		if params[:month] && params[:year] && params[:month] != "0" && params[:year] != "0"
			@articles = Article.where("strftime('%m', created_at) + 0 = ? AND strftime('%Y', created_at) + 0 = ?", 
							                   params[:month].to_i, params[:year].to_i)
			flash.notice = "There are no articles in the period selected" if @articles.empty?
		else
			@articles = Article.all
		end
	end

	def show
		@article = Article.find(params[:id])
		@comment = Comment.new
		@comment.article_id = @article_id
		@article.increment_view_count
		@article.save
	end

	def new
		@article = Article.new
	end

	def create
		# fail / uncomment to see the structure

		# Before including ArticlesHelper:
		# @article = Article.new(params[:article])

		@article = Article.new(article_params)
		@article.author = current_user
		@article.save

		flash.notice = "Article #{@article.title} created"

		redirect_to article_path(@article)
	end

	def destroy
		@article = Article.find(params[:id])
		@article.destroy

		flash.notice = "Article #{@article.title} deleted"

		redirect_to articles_path
	end

	def edit
		@article = Article.find(params[:id])
	end

	def update
		@article = Article.find(params[:id])
		@article.update(article_params)

		flash.notice = "Article #{@article.title} updated"

		redirect_to article_path(@article)
	end

	def most_viewed
		@articles = Article.order(view_count: :desc).limit(3)
		render "index"
	end

	def feed
		@articles = Article.all
		respond_to do |format|
			format.rss { render :layout => false}
		end
	end

end

app/controllers/author_sessions_controller.rb
class AuthorSessionsController < ApplicationController

	def new
	end

	def create
		if login(params[:email], params[:password])
			redirect_back_or_to(articles_path, notice: 'Logged in succesfully')
		else
			flash.now.alert = "Login failed"
			render action: :new
		end
	end

	def destroy
		logout
		redirect_to(:authors, notice: 'Logged out')
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_filter :zero_authors_or_authenticated, only: [:new, :create]
  before_filter :require_login, except: [:new, :create]

  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed' }
      format.json { head :no_content }
    end
  end

  def zero_authors_or_authenticated
    unless Author.count == 0 || current_user
      redirect_to root_path
      return false
    end
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	before_filter :require_login, except: [:create]

	def create
		@comment = Comment.new(comment_params)
		@comment.article_id = params[:article_id]
		@comment.save

		redirect_to article_path(@comment.article)
	end

	def comment_params
		params.require(:comment).permit(:author_name, :body)
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

	before_filter :require_login, only: [:destroy]

	def index
		@tags = Tag.all
	end

	def show
		@tag = Tag.find(params[:id])
	end

	def destroy
		@tag = Tag.find(params[:id])
		@tag.destroy

		flash.notice = "Tag #{@tag.name} deleted"

		redirect_to tags_path
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper

	def article_params
		params.require(:article).permit(:title, :body, :tag_list, :image)
	end
	
	def is_owner?
		@article.author == current_user ? true : false
  	end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper

	def is_admin?
    	current_user.to_s == "admin"
  	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/articles/_article.html.erb
<article class="grid-item">
	<% if article.image.exists? %>
		<%= image_tag article.image.url (:thumb) %>
	<% end %>
	
	<h3><%= link_to article.title, article_path(article) %></h3>
	<div class="post-title">
		<span class="user"><i class="fa fa-user"></i> by <span class="color"><%= article.author %></span></span>
		<span class="created-time"><i class="fa fa-calendar"></i> <%= article.created_at.strftime("%d %b %Y") %></span>
		<span class="views"><i class="fa fa-eye"></i> <%= pluralize article.view_count, "view" %></span>
	</div>
</article>

app/views/articles/_comment.html.erb
<div class="comment">
	<h4>Comment by <span class="color"><%= comment.author_name %></span> -
		<span class="light"><%= comment.created_at.strftime("%d %b %Y  %H:%M") %></span></h4>
	<p><%= comment.body %></p>
	<!-- <p>Posted <%= distance_of_time_in_words(comment.article.created_at, comment.created_at) %> later</p> -->
</div>

app/views/articles/_form.html.erb
<%= form_for(@article, html: { multipart: true }) do |f| %>
	<ul>
		<% @article.errors.full_messages.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.text_area :body, id: "article-body" %>
	</p>
	<p>
		<%= f.label :tag_list %><br />
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<% if @article.image.exists? %>
			<%= image_tag @article.image.url(:medium) %><br />
		<% end %>
		<%= f.label :image, "Attach an image" %><br />
		<%= f.file_field :image %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/edit.html.erb
<div class="section-container">
	<h1>Edit an article</h1>
	<%= render partial: 'form' %>
</div>

app/views/articles/index.html.erb
<div id="grid">
	<%	@articles.reverse.each do |article| %>
		<%= render partial: 'article', locals: { article: article } %>
	<% end %>
</div>

app/views/articles/new.html.erb
<div class="section-container">
	<h1>Create a new article</h1>
	<%= render partial: 'form' %>
</div>

app/views/articles/show.html.erb
<div class="section-container">
	<h1><%= @article.title %></h1>

	<div class="post-article-title">
		<span class="user"><i class="fa fa-user"></i> by <span class="color"><%= @article.author %></span></span>
		<span class="created-time"><i class="fa fa-calendar"></i> <%= @article.created_at.strftime("%d %b %Y") %></span>
		<span class="comments"><a href="#comments"><i class="fa fa-comments"></i><span class="color"> <%= pluralize @article.comments.size, "comment" %> </span></span></a>
	</div>

	<div class="article-body">
		<p class="image"><% if @article.image.exists? %>
				<%= image_tag @article.image.url (:medium) %>
			<% end %>
		</p>
		<p><%= simple_format(@article.body) %></p>
	</div>
	<div class="article-footer">
		<div class="tags">
			Tags: 
			<% @article.tags.each do |tag| %>
				<%= link_to tag.name, tag_path(tag) %>
			<% end %>
		</div>
		<div class="article-actions">
			<% if logged_in? and is_owner? %>
			<i class="fa fa-pencil"></i> <%= link_to "Edit", edit_article_path(@article) %>&nbsp;&nbsp;&nbsp;
			<span class="color"><i class="fa fa-remove"></i></span> <%= link_to "Delete", article_path(@article), 
				method: :delete, 
				data: { confirm: "Are you sure?" } %>
			<% end %>
		</div>
	</div>
</div>

<div class="section-container">
	<a name="comments"></a>
	<h3 class="comments-total">Comments (<%= @article.comments.size %>):</h3>
	<%= render partial: 'articles/comment', collection: @article.comments %>
	<%= render partial: 'comments/form' %>
	<i class="fa fa-arrow-left"></i> <%= link_to "Back to articles list", articles_path %>
</div>

app/views/author_sessions/new.html.erb
<div class="section-container">
	<h1>Login</h1>

	<%= form_tag author_sessions_path, method: :post do %>
		<div class="field">
			<%= label_tag :email %><br />
			<%= text_field_tag :email %>
			<br />
		</div>
		<div class="field">
			<%= label_tag :password %><br />
			<%= password_field_tag :password %>
			<br />
		</div>
		<div class="actions">
			<%= submit_tag "Login" %>
		</div>
	<% end %>

	<i class="fa fa-arrow-left"></i> <%= link_to "Back", articles_path %>
</div>

app/views/authors/_form.html.erb
<%= form_for(@author) do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <span class="color"><h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2></span>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <span class="color"><li>- <%= message %></li></span>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<div class="section-container">
	<h1>Editing Author</h1>

	<%= render 'form' %>

	<i class="fa fa-arrow-left"></i> <%= link_to 'Back', authors_path %> | 
	<i class="fa fa-eye"></i> <%= link_to 'Show', @author %>
</div>

app/views/authors/index.html.erb
<div class="section-container">
  <h1>Listing Authors</h1>

  <table>
    <thead>
      <tr>
        <th>Username</th>
        <th>Email</th>
        <th colspan="3">Action</th>
      </tr>
    </thead>

    <tbody>
      <% @authors.each do |author| %>
        <tr>
          <td><%= author.username %></td>
          <td><%= author.email %></td>
          <td><i class="fa fa-eye"></i> <%= link_to 'View', author %></td>
          <% if is_admin? || author.username.to_s == current_user.to_s %>
            <td><i class="fa fa-pencil"></i> 
              <%= link_to 'Edit', edit_author_path(author) %>
            </td>
            <td><span class="color"><i class="fa fa-remove"></i></span> 
              <%= link_to 'Delete', author, method: :delete, data: { confirm: 'Are you sure?' } %>
            </td>
          <% else %>
            <td><i class="fa fa-pencil"></i> Edit</td>
            <td><span class="color"><i class="fa fa-remove"></i></span> Delete</td>
          <% end %>
          <!-- <td><i class="fa fa-pencil"></i>  -->
            <% link_to_if(current_user.to_s == "admin"  || author.username.to_s == current_user.to_s,
            'Edit', edit_author_path(author)) {} %></td>
          <!-- <td><span class="color"><i class="fa fa-remove"></i></span>  -->
            <% link_to_if(current_user.to_s == "admin"  || author.username.to_s == current_user.to_s,
            'Delete', author, :confirm => 'Are you sure?', :method => :delete) {} %>
          <!-- </td> -->
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <i class="fa fa-user-plus"></i> <%= link_to 'New Author', new_author_path %>
</div>

app/views/authors/new.html.erb
<div class="section-container">
	<h1>New Author</h1>

	<%= render 'form' %>

	<i class="fa fa-arrow-left"></i> <%= link_to 'Back', authors_path %>
</div>

app/views/authors/show.html.erb
<div class="section-container">
	<div class="author-container">
		<div class="author-image">
			<img src="/assets/user.jpg" alt="">
		</div>
		<div class="author-details">
			<h4>Username: <span class="color"><%= @author.username %></span></h4>
			<p>
			  <%= @author.email %>
			</p>
		</div>
	</div>
	
	<i class="fa fa-arrow-left"></i> <%= link_to 'Back', authors_path %> | 
	<i class="fa fa-pencil"></i> <%= link_to 'Edit', edit_author_path(@author) %>
</div>

app/views/comments/_form.html.erb
<div class="post-comment">
	<h3>Post a comment</h3>
	<%= form_for [ @article, @comment] do |f| %>
		<p>
			<%= f.label :author_name, "Your Name" %><br/>
			<%= f.text_field :author_name %>
		</p>
		<p>
			<%= f.label :body, "Your Comment" %><br/>
			<%= f.text_area :body %>
		</p>
		<p>
			<%= f.submit 'Submit' %>
		</p>
	<% end %>
</div>

app/views/layouts/_sidebar.html.erb
<div class="sidebar">

	<div class="sidebar-top">
		<img src="/assets/blogger-logo.jpg" alt="">
	</div>

	<div class="sidebar-menu">
		<% if logged_in? %>
			<div class="main-menu">
				<ul>	
					<li><%= link_to "Articles", articles_path %></li>
					<li><%= link_to "Most viewed", most_viewed_path %></li>
					<li><%= link_to "Create a new article", new_article_path %></li>
					<li><%= link_to "Tags", tags_path %></li>
					<li><%= link_to "Authors", authors_path %></li>
				</ul>
			</div>

			<div class="login-menu">
				<ul>
					<li class="small"><i class="fa fa-user"></i> Logged in as <span class="color"><%= current_user %></span></li>
					<li class="small"><i class="fa fa-key"></i> <%= link_to "Logout", logout_path %> </li>
				</ul>
			</div>	
		<% else %>
			<div class="main-menu">
				<ul>	
					<li><%= link_to "Articles", articles_path %></li>
					<li><%= link_to "Most viewed", most_viewed_path %></li>
					<li><%= link_to "Tags", tags_path %></li>
				</ul>
			</div>

			<div class="login-menu">
				<ul>
					<li class="small"><i class="fa fa-key"></i> <%= link_to "Login", login_path %></li>
				</ul>
			</div>
		<% end %>
	</div>
	
	<div class="archive-menu">	
		Archive: 
		<%= form_tag({controller: "articles", action: "index"}, method: "get") do %>
			<div class="select-style">
	 			<%= select_tag(:month, options_for_select([
	 					['Month', 0], ['January', 1], ['February', 2], ['March', 3], ['April', 4], 
	 					['May', 5], ['June', 6], ['July', 7], ['August', 8], 
	 					['September', 9], ['October', 10], ['November', 11], ['December', 12]], 0)) %>
	 		</div>
			<div class="select-style">
   			<%= select_tag(:year, options_for_select([
   					['Year', 0], ['2016'], ['2017'], ['2018'], 
   					['2019'], ['2020'], ['2021'], ['2022'], 
   					['2023'], ['2024'], ['2025']], 0)) %>
   		</div>
    	<%= submit_tag "Search", :id => "archive-search" %>
		<% end %>		
	</div>

	<div class="rss">
		<a href="https://fcarrara-blogger.herokuapp.com/feed?format=rss"><span class="color"><i class="fa fa-rss-square fa-lg"></i></span> Subscribe</a>	
	</div>

	<div class="sidebar-footer">
		Developed by Fabricio Carrara&nbsp;&nbsp;&nbsp;
			<a href="https://github.com/fcarrara/blogger" target="_blank"><i class="fa fa-github fa-lg"></i></a>
	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Blogger</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	  <link href='https://fonts.googleapis.com/css?family=Oswald:300,400' rel='stylesheet' type='text/css'>
	  <link rel="alternate" type="application/rss+xml" title="Blogger on Rails RSS Feed" href="https://fcarrara-blogger.herokuapp.com/feed?format=rss">
	</head>
	<body>

		<% if flash[:notice] || flash[:warning] %>
		  <div class="alert  <%= 'warning' if flash[:warning] %>" style="display: none">
		    <%= flash[:notice] || flash[:warning] %>
		  </div>
		 <% end %>
	  
		<!-- <p class="flash"><%= flash.notice %></p> -->

		<!-- Sidebar menu -->
		<%= render "layouts/sidebar" %>

		<!-- Articles -->
		<div class="container">
			<%= yield %>		
		</div>

		<!-- <div class="debug-console">
			<%= debug(params) if Rails.env.development? %>
		</div> -->

	</body>
</html>

app/views/tags/index.html.erb
<div class="section-container">
	<h1>All tags</h1>
	<ul class="tags">
		<% @tags.each do |tag| %>
		<li>
			<% if logged_in? %>
				<%= link_to tag_path(tag), 
					method: :delete, 
					data: { confirm: "Are you sure?" } do %>
					<span class="color"><i class="fa fa-remove"></i></span>
				<% end %>
			<% end %>

			&nbsp;&nbsp;&nbsp;<i class="fa fa-hashtag"></i> <%= link_to tag.name.capitalize, tag_path(tag) %>

		</li>
		<% end %>
	</ul>
</div>

app/views/tags/show.html.erb
<div id="grid">
	<%	@tag.articles.each do |article| %>
		<%= render partial: 'articles/article', locals: { article: article } %>
	<% end %>
</div>